apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employee-service.fullname" . }}
  labels:
    app: {{ include "employee-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "employee-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "employee-service.name" . }}
    spec:
      serviceAccountName: {{ include "employee-service.fullname" . }}
      containers:
      - name: employee-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ include "employee-service.fullname" . }}-config
              key: ASPNETCORE_ENVIRONMENT
        - name: EMPLOYEE_SERVICE__CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ include "employee-service.fullname" . }}-secret
              key: EMPLOYEE_SERVICE__CONNECTION_STRING
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.livenessPath }}
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readinessPath }}
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
{{ toYaml .Values.resources | indent 10 }}
