apiVersion: v1
kind: Secret
metadata:
  name: {{ include "employee-service.fullname" . }}-secret
type: Opaque
stringData:
  EMPLOYEE_SERVICE__CONNECTION_STRING: {{ .Values.secret.connectionString | quote }}
