apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: employee-api
  description: Employee API service
  tags:
    - api
    - employee
    - dotnet
    - webapi
    - idp-learning
spec:
  type: service
  lifecycle: development
  owner: guest
  providesApis:
    - employee-api
